baseURL = 'https://machw-lab.github.io/'
languageCode = 'en-us'
title = 'MachW Lab'

[languages.en]
copyright = ""
languagecode = "en-us"
languagedirection = "ltr"
languagename = "English"
title = ""
weight = 10

[languages.en.params.paige.site]
description = ""

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false
style = "github"

[[module.imports]]
path = "github.com/willfaught/paige"

[params.paige.pages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_toc = true
disable_word_count = true

[paige.pages.base_schema]
isAccessibleForFree = true
isFamilyFriendly = true

[params.paige.site]
disable_breadcrumbs = true
disable_credit = true

[params.paige.subpages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true
disable_word_count = true

[taxonomies]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 20
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 30

[permalinks]
  team = "/team/"
  publications = "/publications/"

[params.paige]
  css = ["css/custom.css"]